### ISSUE TITLE
Ignore this

### ISSUE THREAD

**Issue by GabrielBigardi** [cathei/AntiScriptableObjectArchitecture#4]

**Comment by cathei** [comment]
> Scriptable objects are great for keeping data

> It's pretty easy to expand on existing scriptable objects

> Dependency Injection has nothing to do with SOs

> you hate scriptable objects and doesn't know it's full potential

Are you understanding this repository is about `Anti ScriptableObject Architecture` not `Anti ScriptableObject as data asset in general`? Did you check the links that explains what is "SOA"? I don't think you are understanding this repo at all. You wouldn't say those. All the statements on this issue is pointing somewhere else.

> No, people shouldn't use them for EVERYTHING, i recommend using them for storing data, having pre-defined objects (like items, player/enemy data, among other things)

This is the point that this repo is trying to emphasize. I thought you are trying to oppose, not agree with it?

**Comment by cathei** [comment]
Going to close this issue because whole issue is based on misunderstanding. Reopen or create new issue if you do have more opinion. I'll try to rephrase readme to be more clear as well.
